# Week 3 Assignment
* Download the "Week_3_Assignment.ipynb" notebook 
* Fill in the code in the cells marked with `# YOUR ANSWER HERE:` by answering the question/task defined in the cell above it starting with `GRADED:`
* Code cells outside of `# YOUR ANSWER HERE:` will not be considered for grading. 
  * Feel free to write outside of it for debugging
* Submit the updated notebook
  * Make sure to save your changes before submitting it!

In [47]:
# PLEASE, DO NOT MODIFY THIS CELL!

# IMPORT NECESSARY LIBRARIES AND DATA
import pandas as pd
import numpy as np

# SECTION A data
nparr = np.arange(2, 74).reshape(6, 12)
display(nparr)

# SECTION B data
data_url = 'https://raw.githubusercontent.com/plotly/datasets/master/2011_february_us_airport_traffic.csv'
df = pd.read_csv(data_url, header=0)
df.head()

array([[ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13],
       [14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37],
       [38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61],
       [62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73]])

iata                            airport               city state country  \
0  ORD       Chicago O'Hare International            Chicago    IL     USA   
1  ATL  William B Hartsfield-Atlanta Intl            Atlanta    GA     USA   
2  DFW    Dallas-Fort Worth International  Dallas-Fort Worth    TX     USA   
3  PHX   Phoenix Sky Harbor International            Phoenix    AZ     USA   
4  DEN                        Denver Intl             Denver    CO     USA   

         lat        long    cnt  
0  41.979595  -87.904464  25129  
1  33.640444  -84.426944  21925  
2  32.895951  -97.037200  20662  
3  33.434167 -112.008056  17290  
4  39.858408 -104.667002  13781

## GRADED SECTION A

1. Determine the size, number of dimensions and type of elements in the numpy array `nparr`
2. Determine the variance of all elements in `nparr`
3. Determine the position (not the value) of the maximum value element in `nparr`
4. Create an array of the same shape as `nparr` but filled with zeros
5. Create an array of the same shape as `nparr` but filled with tens
6. Create an array of the same shape as `nparr` but where every element is the natural logarithm of the original element
7. Create an array result of shape `6` by `6` resulting from multiplication of nparr with transpose(`nparr`). Hint: use `np.dot`
8. Create an array `prime_arr` to save all the prime numbers in `nparr` using vectorize function.

In [100]:
# YOUR SECTION A ANSWER HERE (please use comments to number each of your answers)

# Q1: Size of the array : Number of elements present in array
print(nparr.size)

# Q1-1: Number of Dimensions
print(nparr.ndim)

# Q1-2: Type of elements
print(nparr.dtype)


# Q2: Variance with numpy of nparr
print('nparr :', nparr)
print('Variance of nparr:', np.var(nparr))

# Q3: Find the maximun value of nparr????????????????
a,b = np.unravel_index(nparr.argmax(), nparr.shape)
print(a,b)


# Q4: nparr filled with Zeros
nparr = np.zeros((6,12), dtype=np.int32)
print(nparr)

# Q5: nparr filled with tens
nparr_tens = np.multiply(np.ones(nparr.shape),10)
print(nparr_tens)

# Q-6 nparr calculate every element in the array with the natural logarithm of the original element
nparr = np.arange(2, 74).reshape(6, 12)
display(nparr)
arr=np.array(nparr)
nparr_1 = np.log(arr)
print(nparr_1)

# Q:7 Create an array result of shape 6 by 6 resulting from multiplication of nparr with transpose(nparr). 
#Hint: use np.dot

result_shape_6by6 = np.dot(nparr, np.transpose(nparr))
print(result_shape_6by6)

# Q:8 Create an array prime_arr to save all the prime numbers in nparr using vectorize function.


def prime_number(number):
    prime_num = True
    for i in range(2,number):
        if(number%i == 0):
            prime_num = False
    return prime_num

prime_num_vector = np.vectorize(prime_number)
nparr[prime_num_vector(nparr)]

72
2
int32
nparr : [[ 2  3  4  5  6  7  8  9 10 11 12 13]
 [14 15 16 17 18 19 20 21 22 23 24 25]
 [26 27 28 29 30 31 32 33 34 35 36 37]
 [38 39 40 41 42 43 44 45 46 47 48 49]
 [50 51 52 53 54 55 56 57 58 59 60 61]
 [62 63 64 65 66 67 68 69 70 71 72 73]]
Variance of nparr: 431.9166666666667
5 11
[[0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0]]
[[10. 10. 10. 10. 10. 10. 10. 10. 10. 10. 10. 10.]
 [10. 10. 10. 10. 10. 10. 10. 10. 10. 10. 10. 10.]
 [10. 10. 10. 10. 10. 10. 10. 10. 10. 10. 10. 10.]
 [10. 10. 10. 10. 10. 10. 10. 10. 10. 10. 10. 10.]
 [10. 10. 10. 10. 10. 10. 10. 10. 10. 10. 10. 10.]
 [10. 10. 10. 10. 10. 10. 10. 10. 10. 10. 10. 10.]]


array([[ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13],
       [14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37],
       [38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61],
       [62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73]])

[[0.69314718 1.09861229 1.38629436 1.60943791 1.79175947 1.94591015
  2.07944154 2.19722458 2.30258509 2.39789527 2.48490665 2.56494936]
 [2.63905733 2.7080502  2.77258872 2.83321334 2.89037176 2.94443898
  2.99573227 3.04452244 3.09104245 3.13549422 3.17805383 3.21887582]
 [3.25809654 3.29583687 3.33220451 3.36729583 3.40119738 3.4339872
  3.4657359  3.49650756 3.52636052 3.55534806 3.58351894 3.61091791]
 [3.63758616 3.66356165 3.68887945 3.71357207 3.73766962 3.76120012
  3.78418963 3.80666249 3.8286414  3.8501476  3.87120101 3.8918203 ]
 [3.91202301 3.93182563 3.95124372 3.97029191 3.98898405 4.00733319
  4.02535169 4.04305127 4.06044301 4.07753744 4.09434456 4.11087386]
 [4.12713439 4.14313473 4.15888308 4.17438727 4.18965474 4.20469262
  4.21950771 4.2341065  4.24849524 4.26267988 4.27666612 4.29045944]]
[[  818  1898  2978  4058  5138  6218]
 [ 1898  4706  7514 10322 13130 15938]
 [ 2978  7514 12050 16586 21122 25658]
 [ 4058 10322 16586 22850 29114 35378]
 [ 5138 13130 21122 29

array([ 2,  3,  5,  7, 11, 13, 17, 19, 23, 29, 31, 37, 41, 43, 47, 53, 59,
       61, 67, 71, 73])

## GRADED SECTION B

The dataframe `df` loads the dataset that contains information on a number of categories regarding traffic (variable `cnt` represents the actual traffic) at US airports from February 2011.
The dataset has already been loaded for you in the first code cell above.
 1. Rename column 'long' as 'longitude', and 'lat' as 'latitude'
 2. Print the number of rows for the subset of the dataframe for which traffic values are higher than `15,000` and lower than `25,000`. Please print those rows as well.
 3. Print the names of all the columns of the dataframe
 4. Print a subset of the dataframe containing the `100th` and the `10th` rows of the original dataframe (`in that order`).
 5. Which US `state` has the largest __total__ airport traffic? Which state has the least total airport traffic?
 6. Which state has the most __total__ number of airports?
 7. Of the states that have at least 9 airports, which one has the least total traffic for all airports?
 8. What is the total airport traffic for all states that border the state of Virginia?
 9. Generate a new column 'intl'- a binary feature which stores 'True' or 'False' based on whether it's an international airport or not. And find which state has the most number of international airports.

In [87]:
# YOUR SECTION B ANSWER HERE (please use comments to number each of your answers)

#Q1:Rename column 'long' as 'longitude', and 'lat' as 'latitude'
df.rename(columns={'long':'longitude','lat':'latitude'}, inplace=True)

##Q2:Print the number of rows for the subset of the dataframe for which traffic values are higher than
#    15,000 and lower than 25,000. Please print those rows as well.

traf_subset=df[(df["cnt"] > 15000) & (df["cnt"] < 25000)]
print(traf_subset.shape[0]) 
print(traf_subset)
print(df.columns)

##Q3:Print the names of all the columns of the dataframe
print(df.columns)

##Q4:Print a subset of the dataframe containing 
#   the 100th and the 10th rows of the original dataframe (in that order)

one_100=df.iloc[[99,9]] #df first row starts with index 0
print(one_100)

##Q5:Which US state has the largest total airport traffic? 
#   Which state has the least total airport traffic?
df['state_totals'] = df.groupby('state')['cnt'].transform('sum')
max= df.loc[df['state_totals'].idxmax()]['state']
print(max)
min= df.loc[df['state_totals'].idxmin()]['state']
print(min)

##Q6:Which state has the most total number of airports?
df['airport_count'] = df.groupby('state')['airport'].transform('nunique')
max_arpt_state= df.loc[df['airport_count'].idxmax()]['state']
print(max_arpt_state)

##Q7: Of the states that have at least 9 airports, 
#    which one has the least total traffic for all airports?
n9_arpt=df[(df["airport_count"] >= 9)]
print(n9_arpt.loc[n9_arpt['state_totals'].idxmin()]['state'])

##Q8: What is the total airport traffic for all states that border the state of Virginia?
Boader_of_virginia=np.array(["NC","TN","KY","WV","MD"])
Boader_of_virginia=df[df['state'].isin(Boader_of_virginia)]
print(Boader_of_virginia['cnt'].sum(axis=0))

##Q9: Generate a new column 'intl'- a binary feature which stores 'True' or 'False' based on whether
#     it's an international airport or not. And find which state has the most number of international airports.
df['intl'] = np.where(df['airport'].str.contains("Intl|International", case=False), True, False)
df['intl_airport_count']= df.groupby('state')['intl'].transform('sum')
max_state_intlairport= df.loc[df['intl_airport_count'].idxmax()]['state']
print(max_state_intlairport)


3
  iata                            airport               city state country  \
1  ATL  William B Hartsfield-Atlanta Intl            Atlanta    GA     USA   
2  DFW    Dallas-Fort Worth International  Dallas-Fort Worth    TX     USA   
3  PHX   Phoenix Sky Harbor International            Phoenix    AZ     USA   

    latitude   longitude    cnt  state_totals  airport_count  intl  \
1  33.640444  -84.426944  21925       23183.0            6.0  True   
2  32.895951  -97.037200  20662       48957.0           17.0  True   
3  33.434167 -112.008056  17290       20703.0            3.0  True   

   intl_airport_count  
1                 2.0  
2                10.0  
3                 3.0  
Index(['iata', 'airport', 'city', 'state', 'country', 'latitude', 'longitude',
       'cnt', 'state_totals', 'airport_count', 'intl', 'intl_airport_count'],
      dtype='object')
Index(['iata', 'airport', 'city', 'state', 'country', 'latitude', 'longitude',
       'cnt', 'state_totals', 'airport_count', 'in